# Generated by Django 4.2.10 on 2024-02-19 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projStatus', models.CharField(max_length=50, null=True)),
                ('propertyImage1', models.ImageField(blank=True, null=True, upload_to='')),
                ('propertyImage2', models.ImageField(blank=True, null=True, upload_to='')),
                ('propertyImage3', models.ImageField(blank=True, null=True, upload_to='')),
                ('projectName', models.CharField(max_length=50)),
                ('projectType', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(max_length=1100)),
                ('directions', models.URLField(default=None)),
                ('developmentSize', models.FloatField(default=None)),
                ('noOfUnits', models.IntegerField(default=None)),
                ('bedrooms', models.CharField(default=None, max_length=50)),
                ('about', models.TextField(default=None)),
                ('unitPlan1', models.ImageField(blank=True, upload_to='')),
                ('unitPlan2', models.ImageField(blank=True, upload_to='')),
                ('structure', models.TextField(default=None)),
                ('lobby', models.TextField(default=None)),
                ('lifts', models.TextField(default=None)),
                ('apartmentFlooring', models.TextField(default=None)),
                ('kitchen', models.TextField(default=None)),
                ('utility', models.TextField(default=None)),
                ('toiletsNFittings', models.TextField(default=None)),
                ('painting', models.TextField(default=None)),
                ('doorsNWindows', models.TextField(default=None)),
                ('electrical', models.TextField(default=None)),
                ('securitySystem', models.TextField(default=None)),
                ('dgBackup', models.TextField(default=None)),
            ],
        ),
    ]
